services: 
  postgres:
    container_name: wish-list-movies
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: wishlistmov
      PDDATA: /data/postgres
    volumes: 
      - ./data/pg:/data/postgres